../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/Erwin.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/SallandAutopilot.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/LisaQuadAsctecB2_v1_1_Booz001.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/EasyStartPanTiltCHIMU_SPI.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/MicrojetBR.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/MentorEnergy.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/MicrojetBRimu.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/logger_sd_xbee_9k6.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/NavgoV3.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/holiday_LisaM_Aspirin1_5_fixeW.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/skywalkerfiber.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/TwinStarXSens.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/tudelft_EasyStarOrange.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/skywalker.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/Mentor.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/LisaAspirin2.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/EasyStarTinySense.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/openuas_discovery.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/MicrojetCDW.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/NoArmsLisaLQuadMKKB2_Aspirin2.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/quadrotor_lisa_m_2_pwm_hbk_ppm.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/c172.xml 1 2
../../sw/tools/airframe_editor/xml_airframe.py ./TUDelft/TwinjetAspirinI2C.xml 1 2
