#
# Copyright (C) 2012 - TU Delft Robotics Minor - Dino Hensen <dino.hensen@gmail.com> and Freek van Tienen
#
# Minimal makefile for arm-none-linux-gnueabi toolchain. Assuming installed in default installation.
# todo: make it dynamically find the toolchain

CXX = $(shell which arm-linux-gnueabi-g++)
CC = $(shell which arm-linux-gnueabi-gcc)
LD = $(shell which arm-linux-gnueabi-gcc)
AR = $(shell which arm-linux-gnueabi-ar)
CP = $(shell which arm-linux-gnueabi-objcopy)
DMP = $(shell which arm-linux-gnueabi-objdump)
NM = $(shell which arm-linux-gnueabi-nm)
SIZE = $(shell which arm-linux-gnueabi-size)
GDB = $(shell which arm-linux-gnueabi-gdb)
TOOLCHAIN_DIR=/usr/arm-linux-gnueabi
GCC_LIB_DIR=$(TOOLCHAIN_DIR)/lib

# checking if gcc has thumb2 instruction
MULTILIB = $(shell if $(CC) --print-multi-lib | grep thumb2 > /dev/null ; then echo "yes"; else echo "no"; fi)

# some general commands
RM = rm

@echo "Using CC = $(CC)"

CFLAGS += -I/usr/arm-linux-gnueabi/include

