
# Actuator drivers for the bebop

ACUTATORS_SPEKTRUM_OUT ?= UART2
ACUTATORS_SPEKTRUM_OUT_UPPER =$(shell echo $(ACUTATORS_SPEKTRUM_OUT) | tr a-z A-Z)
ACUTATORS_SPEKTRUM_OUT_LOWER =$(shell echo $(ACUTATORS_SPEKTRUM_OUT) | tr A-Z a-z)

ACTUATORS_SPEKTRUM_CFLAGS  += -DACUTATORS_SPEKTRUM_DEV=$(ACUTATORS_SPEKTRUM_OUT_LOWER) -DUSE_$(ACUTATORS_SPEKTRUM_OUT_UPPER)

ap.CFLAGS += -DACTUATORS $(ACTUATORS_SPEKTRUM_CFLAGS)
ap.srcs   += subsystems/actuators/actuators_spektrum.c
