
# Actuator drivers for the bebop

ACUTATOR_SPEKTRUM_OUT ?= UART2
ACUTATOR_SPEKTRUM_OUT_UPPER =$(shell echo $(ACUTATOR_SPEKTRUM_OUT) | tr a-z A-Z)
ACUTATOR_SPEKTRUM_OUT_LOWER =$(shell echo $(ACUTATOR_SPEKTRUM_OUT) | tr A-Z a-z)

ACTUATOR_SPEKTRUM_CFLAGS  += -DACUTATOR_SPEKTRUM_DEV=$(ACUTATOR_SPEKTRUM_OUT_LOWER) -DUSE_$(ACUTATOR_SPEKTRUM_OUT_UPPER)

ap.CFLAGS += -DACTUATORS $(ACTUATOR_SPEKTRUM_CFLAGS)
ap.srcs   += subsystems/actuators/actuators_spektrum.c
